@startuml

object "<u>textbook1 : Textbook</u>" as textbook1{
    -title = Clean Code
    -author = Robert C. Martin
    -publisher = Prentice Hall
}

object "<u>instructor1 : Instructor</u>" as instructor1{
    -firstName = Nima
    -lastName = Davarpanah
    -officeNumber = BD9 - 302
}


object "<u>course : Course</u>" as course {
     courseName = CS3560
}

textbook1 --o course::Textbook1
instructor1 --o course::Instructor1
@enduml