@startuml

object "textbook1 : Textbook" as textbook1{
    -title = Clean Code
    -author = Robert C. Martin
    -publisher = Prentice Hall
}

object "instructor1 : Instructor" as instructor1{
    -firstName = Nima
    -lastName = Davarpanah
    -officeNumber = BD9 - 302
}


object "course : Course" as course {
     courseName = CS3560
}

textbook1 --o course::Textbook1
instructor1 --o course::Instructor1
@enduml